export const SET_ERRORS = "SET_ERRORS";
export const LOADING = "LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING";
export const SET_CREATED_MESSAGE = "SET_CREATED_MESSAGE";
export const SET_ROOMS = "SET_ROOMS";

export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const SET_SONGS = "SET_SONGS";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
